[package]
name = "crypto-msg-parser"
version = "1.0.1"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2018"
description   = "Parse websocket messages"
license = "Apache-2.0"
repository = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-msg-parser"
keywords = ["cryptocurrency", "blockchain", "trading"]

[dependencies]
chrono = "0.4"
crypto-market-type = "0.1.2"
crypto-pair = "2.0.1"
lazy_static = "1"
reqwest = { version = "0.10", features = ["blocking", "gzip"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.20"
strum_macros = "0.20"

[dev-dependencies]
float-cmp = "0.8.0"
