[package]
name = "crypto-msg-parser"
version = "1.9.7"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2021"
description = "Parse websocket messages from cryptocurreny exchanges"
license = "Apache-2.0"
repository = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-msg-parser"
keywords = ["cryptocurrency", "blockchain", "trading"]

[dependencies]
chrono = "0.4"
crypto-contract-value = "1.3.4"
crypto-market-type = "1.0.8"
crypto-msg-type = "1.0.5"
crypto-pair = "2.2.0"
if_chain = "1"
once_cell = "1"
reqwest = { version = "0.11", features = ["blocking", "gzip"] }
simple-error = "0.2.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
float-cmp = "0.8.0"
