[package]
name = "crypto-msg-parser"
version = "2.7.8"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2021"
description = "Parse websocket messages from cryptocurreny exchanges"
license = "Apache-2.0"
repository = "https://github.com/crypto-crawler/crypto-msg-parser/tree/main/crypto-msg-parser"
keywords = ["cryptocurrency", "blockchain", "trading"]

[dependencies]
chrono = "0.4.22"
crypto-contract-value = "1.6.0"
crypto-market-type = "1.1.3"
crypto-msg-type = "1.0.10"
crypto-message = "1.1.14"
crypto-pair = "2.3.4"
if_chain = "1.0.2"
once_cell = "1.15.0"
reqwest = { version = "0.11.12", features = ["blocking", "gzip"] }
simple-error = "0.2.3"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
strum = "0.24.1"
strum_macros = "0.24.3"
