[package]
name = "crypto-msg-parser"
version = "2.8.10"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2021"
description = "Parse websocket messages from cryptocurreny exchanges"
license = "Apache-2.0"
repository = "https://github.com/crypto-crawler/crypto-msg-parser/tree/main/crypto-msg-parser"
keywords = ["cryptocurrency", "blockchain", "trading"]

[dependencies]
chrono = "0.4.23"
crypto-contract-value = "1.7.2"
crypto-market-type = "1.1.5"
crypto-msg-type = "1.0.11"
crypto-message = "1.1.16"
crypto-pair = "2.3.9"
if_chain = "1.0.2"
once_cell = "1.16.0"
reqwest = { version = "0.11.13", features = ["blocking", "gzip"] }
simple-error = "0.2.3"
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.91"
strum = "0.24.1"
strum_macros = "0.24.3"
