[package]
name = "crypto-msg-parser"
version = "2.8.26"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2021"
description = "Parse websocket messages from cryptocurreny exchanges"
license = "Apache-2.0"
repository = "https://github.com/crypto-crawler/crypto-msg-parser/tree/main/crypto-msg-parser"
keywords = ["cryptocurrency", "blockchain", "trading"]

[dependencies]
chrono = "0.4.23"
crypto-contract-value = "1.7.13"
crypto-market-type = "1.1.5"
crypto-msg-type = "1.0.11"
crypto-message = "1.1.17"
crypto-pair = "2.3.13"
if_chain = "1.0.2"
once_cell = "1.17.1"
reqwest = { version = "0.11.14", features = ["blocking", "gzip"] }
simple-error = "0.3.0"
serde = { version = "1.0.155", features = ["derive"] }
serde_json = "1.0.94"
strum = "0.24.1"
strum_macros = "0.24.3"
