[package]
name = "crypto-msg-parser"
version = "1.5.0"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2021"
description = "Parse websocket messages from cryptocurreny exchanges"
license = "Apache-2.0"
repository = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-msg-parser"
keywords = ["cryptocurrency", "blockchain", "trading"]

[dependencies]
chrono = "0.4"
crypto-contract-value = "1.0.5"
crypto-market-type = "0.1.6"
crypto-pair = "2.0.6"
lazy_static = "1"
reqwest = { version = "0.11", features = ["blocking", "gzip"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.20"
strum_macros = "0.20"

[dev-dependencies]
float-cmp = "0.8.0"
