[workspace]
members = [
  "crypto-client",
  "crypto-pair",
  "crypto-markets",
  "crypto-market-type",
  "crypto-msg-parser",
  "crypto-rest-client",
  "crypto-ws-client",
  "crypto-crawler",
  "carbonbot",
]
