[package]
name = "crypto-pair"
version = "2.2.1"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2021"
description = "Parse exchange-specific symbols to unified format"
license = "Apache-2.0"
repository = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-pair"
homepage = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-pair"

[dependencies]
crypto-market-type = "1.0.8"
once_cell = "1.10.0"
reqwest = { version = "0.11.10", features = ["blocking", "gzip"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
