[package]
name = "crypto-pair"
version = "1.0.1"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2018"
description   = "Normalize cryptocurrency trade pairs"
license = "Apache-2.0"
repository = "https://github.com/soulmachine/crypto-crawler-rs"
homepage = "https://github.com/soulmachine/crypto-crawler-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"

[dev_dependencies]
serde_json = "1.0"
