[package]
name = "crypto-pair"
version = "2.1.2"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2021"
description = "Parse exchange-specific symbols to unified format"
license = "Apache-2.0"
repository = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-pair"
homepage = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-pair"

[dependencies]
crypto-market-type = "1.0.5"
lazy_static = "1"
reqwest = { version = "0.11", features = ["blocking", "gzip"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
