[package]
name = "crypto-pair"
version = "2.0.6"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2021"
description   = "Normalize cryptocurrency trading pairs"
license = "Apache-2.0"
repository = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-pair"
homepage = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-pair"

[dependencies]
lazy_static = "1"
reqwest = { version = "0.11", features = ["blocking", "gzip"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
