name: CI

on: [push, pull_request]

jobs:
    build:
        name: Cargo build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --release --all-features
    test:
        name: Cargo test
        runs-on: ubuntu-latest
        env:
            MXC_ACCESS_KEY: ${{ secrets.MXC_ACCESS_KEY }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - uses: actions-rs/cargo@v1
              with:
                  command: test
    fmt:
        name: Cargo fmt
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
                  components: rustfmt
            - uses: actions-rs/cargo@v1
              with:
                  command: fmt
                  args: -- --check

    check:
        name: Cargo check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - uses: actions-rs/cargo@v1
              with:
                  command: check

    clippy:
        name: Cargo clippy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
                  components: clippy
            - uses: actions-rs/cargo@v1
              with:
                  command: clippy
